name: Update README

on:
  push:
    paths:
      - 'Queries/**' # Trigger the workflow when files are added, modified, or deleted in the 'Queries' directory
      - 'Ideas/**' # Trigger the workflow when files are added, modified, or deleted in the 'Ideas' directory

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch origin

      - name: Merge or rebase changes
        run: git merge origin/main

      - name: Update README
        run: |
          echo "# My GitHub Repository" > README.md
          echo "" >> README.md
          echo "This repository contains various files with data." >> README.md
          echo "" >> README.md
          echo "## Data Files" >> README.md
          echo "" >> README.md
          echo "### Queries" >> README.md
          echo "" >> README.md
          echo "<details>" >> README.md
          echo "<summary>Click to expand</summary>" >> README.md
          echo "" >> README.md
          find Queries -type f -exec sh -c "echo \"- [\$(basename {})](https://github.com/ankkp/ARGQuery/blob/main/Queries/{})\"" \; >> README.md
          echo "" >> README.md
          echo "</details>" >> README.md
          echo "" >> README.md
          echo "### Ideas" >> README.md
          echo "" >> README.md
          echo "<details>" >> README.md
          echo "<summary>Click to expand</summary>" >> README.md
          echo "" >> README.md
          find Ideas -type f -exec sh -c "echo \"- [\$(basename {})](https://github.com/ankkp/ARGQuery/blob/main/Ideas/{})\"" \; >> README.md
          echo "" >> README.md
          echo "</details>" >> README.md

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pull remote changes
        run: git pull origin main

      - name: Resolve conflicts (if any)
        run: |
          # You can add commands here to automatically resolve conflicts, if possible,
          # or manually resolve the conflicts in the affected files.

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Merge remote changes"
          git push origin main
