name: Update README

on:
  push:
    paths:
      - '**' # Trigger the workflow when any file is added, modified, or deleted

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "# My GitHub Repository" > README.md
          echo "" >> README.md
          echo "This repository contains various files with data." >> README.md
          echo "" >> README.md
          echo "## Data Files" >> README.md
          echo "" >> README.md
          find . -type f -not -path "./.github/*" -not -name "README.md" -exec sh -c "echo \"- [\$(basename {})]({})\"" \; >> README.md

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update README"
          git push
